import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Aman from '@/components/Aman'
import Footer from '@/components/Footer'
import { motion } from 'framer-motion'
import { useState } from 'react'
import Menu from '@/components/Menu'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [lightMode , setLightMode] = useState(true)
  const [isOpen , setIsOpen] = useState(false)
    const pullData = (data)=>{
    setLightMode(data)
  }
  const pullData2 = (data2)=>{
    setIsOpen(data2)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar pullData = {pullData} pullData2 = {pullData2}/>
        <Aman lightMode={lightMode} setLightMode = {setLightMode}/>
        <Footer lightMode={lightMode} setLightMode = {setLightMode}/>
        <motion.div className={styles.hire}
        animate = {{color : ['#34e7e4' , '#ef5777' , '#ff5e57' , '#ffd32a' , '#c56cf0' , '#32ff7e']}}
        transition={{repeat : Infinity , duration : 1}}
        >Hire me</motion.div>
        { isOpen && <Menu/>}
      </main>
    </>
  )
}
