import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import styles from '@/styles/Projects.module.css'
import Head from 'next/head'
import Image from 'next/image';
import signIn from '../public/signIn.png'
import Link from 'next/link';
import Github from '@/components/Github';
import { motion } from 'framer-motion'
import portfolio1 from '../public/portfolio1.png'
import joker from '../public/joker.png'
import portfolio2 from '../public/portfolio2.png'
import { useState } from 'react';
const variant = {
    initial : {
        opacity : 0
    },
    animate : {
        opacity : 1,
        transition : {
            duration:.8
        }
    }
}
const Projects = () => {
    const [lightMode , setLightMode] = useState(true)
  const pullData = (data)=>{
    setLightMode(data)
  }
    return ( 
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={lightMode ? `${styles.projects}` : `${styles.darkProjects}`}>
                <Navbar pullData={pullData}/>
                <motion.div className={styles.projectsTitle} 
                variants={variant}
                initial = "initial"
                animate = "animate"
                >
                    <div className={styles.titleText}>Imagination</div>
                    <div className={styles.titleText}>trumps</div>
                    <div className={styles.titleText}>Knowledge!</div>

                </motion.div>
                <div className={styles.projectsDetails}>
                    <div className={lightMode ? `${styles.card1}` : `${styles.darkCard1}`}>
                        <div className={styles.cardBox}>
                            <div className={styles.imageBox}>
                                <motion.div className={styles.imageBox1}
                                 whileHover={{
                                    scale : 1.1
                                 }}
                                ><Image className={styles.signIn} src={signIn} alt='signIn'/></motion.div>
                            </div>
                            <div className={styles.textBox}>
                                <div className={styles.text1}>Featured Project</div>
                                <div className={styles.text2}>SignIn Landing Project</div>
                                <p className={styles.text3}>
                                A feature-rich signIn App using React, Next, Context API, React Router and Recharts. 
                                </p>
                                <div className={styles.icons}>
                                    <div className={styles.github}><Link href="https://github.com/the-day-dreamer/signin" target='_blank'><Github/></Link></div>
                                    <button className={styles.button}><Link href="https://signin-beige.vercel.app/" target='_blank'>Visit project</Link></button>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div className={styles.cardContainer}>
                        <div className={lightMode ? `${styles.card2}` : `${styles.darkCard2}`}>
                            <div className={styles.cardImage}>
                                <motion.div className={styles.cardImageBox}
                                whileHover={{
                                    scale : 1.1
                                }}
                                >
                                    <Image src={portfolio1} alt='portfolio1' className={styles.portfolio1}/>
                                </motion.div>
                            </div>
                            <div className={styles.cardText}>
                                <div className={styles.cardTextTitle}>portfolio website</div>
                                <div className={styles.cardTextIcons}>
                                    <div className={styles.githubIcon}><Link href="https://github.com/the-day-dreamer/portfolio" target='_blank'><Github/></Link></div>
                                    <div className={styles.visitText}><Link href="https://portfolio-three-gules-51.vercel.app/" target='_blank'>Visit</Link></div>
                                </div>
                            </div>
                        </div>
                        <div className={lightMode ? `${styles.card3}` : `${styles.darkCard3}`}>
                        <div className={styles.cardImage}>
                                <motion.div className={styles.cardImageBox}
                                whileHover={{
                                    scale : 1.1
                                }}
                                >
                                    <Image src={joker} alt='portfolio1' className={styles.portfolio1}/>
                                </motion.div>
                            </div>
                            <div className={styles.cardText}>
                                <div className={styles.cardTextTitle}>quotes app</div>
                                <div className={styles.cardTextIcons}>
                                    <div className={styles.githubIcon}><Link href="https://github.com/the-day-dreamer/quotes-app" target='_blank'><Github/></Link></div>
                                    <div className={styles.visitText}><Link href="https://quotes-n06zbmylu-the-day-dreamer.vercel.app/" target='_blank'>Visit</Link></div>
                                </div>
                                </div>
                        </div>

                    </div>
                    <div className={lightMode ? `${styles.card1}` : `${styles.darkCard1}`}>
                        <div className={styles.cardBox}>
                            <div className={styles.imageBox}>
                                <motion.div className={styles.imageBox1}
                                 whileHover={{
                                    scale : 1.1
                                 }}
                                ><Image className={styles.signIn} src={portfolio2} alt='signIn'/></motion.div>
                            </div>
                            <div className={styles.textBox}>
                                <div className={styles.text1}>Featured Project</div>
                                <div className={styles.text2}>Improved portfolio project</div>
                                <p className={styles.text3}>
                                A feature-rich signIn App using React, Next, Context API, React Router and Recharts. 
                                </p>
                                <div className={styles.icons}>
                                    <div className={styles.github}><Link href="https://github.com/the-day-dreamer/portfolio2" target='_blank'><Github/></Link></div>
                                    <button className={styles.button}><Link href="https://portfolio2-two-psi.vercel.app/" target='_blank'>Visit project</Link></button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <Footer/>
            </main>
        </>
     );
}
 
export default Projects
